# 指定服务名称
server:
  port: 8201
spring:
  application:
    name: client-01 #实例名称
  cloud:
    config:
      name: application #配置文件
      profile: client-01  #环境名
      label: master #配置文件所在分支
      discovery:
        enabled: true #开启配置服务发现
        service-id: config #配置服务实例名称
      uri: http://localhost:8888/eureka #配置服务中心



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
      instance:
        prefer‐ip‐address: true #可以跨域访问
        instance-id: client-01
        #定义服务任务续约的调用间隔时间
        lease-renewal-interval-in-seconds: 5
        #定义服务失效时间
        lease-expiration-duration-in-seconds: 10
        #实例信息的元数据